### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by WolfDen133** [DMXControl/ArtNetSharp#2]
Hiya, not really an issue, but I wanted to use this package in a project im working on but struggling to figure it out, do you have any documentation for this package, or let me know how to use it?

Heres my discord if you don't want to talk here: wolfden133

**Comment by patrick-dmxc** [comment]
https://github.com/DMXControl/ArtNetSharp#quickstart

**Comment by patrick-dmxc** [comment]
I wrote some Examples, maybe this is enough to start.
If not just ask

**Comment by WolfDen133** [comment]
Cheers man, thanks for the wicked project

**Comment by WolfDen133** [comment]
Could you explain to me a bit more how to get this working, I cant seem to get it to work :(

**Comment by patrick-dmxc** [comment]
What you want to do,
Controller or node?

If you want to send DMX you need to no dmx is only send if there is a Node with matching Config in the Network. So the Controller Poll for available Nodes and then send Unicasts to Nodes.

Use Wireshark and filter for artnet to see all Network Messages

**Comment by WolfDen133** [comment]
Sweet thank you.
